--SQL Lab for Revature Week 2
--Due Monday May 14, 2018

--1.0 Set-up and run Chinook.sql

--2.0 SQL Queries
---2.1 SELECT

SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LASTNAME='King';
SELECT * FROM EMPLOYEE WHERE FIRSTNAME='Andrew' AND REPORTSTO IS NULL;

---2.2 ORDER BY
SELECT * FROM ALBUM ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

---2.3 INSERT INTO

--Insert 2 new records into GENRE table
INSERT INTO GENRE (GENREID,NAME) 
    VALUES (26,'Funk');
INSERT INTO GENRE (GENREID,NAME) 
    VALUES (27,'EDM');
--Insert 2 new records into EMPLOYEE table
INSERT INTO EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME,TITLE,REPORTSTO,BIRTHDATE,HIREDATE,
        ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,FAX,EMAIL) 
    VALUES (9,'Martin','Kyle','Associate',1,'02-JUL-88','30-APR-18','100 Stone Mill Run',
        'Athens','GA','USA','30605','+1 (678) 315-0635','+1 (678) 315-0635','knm350@gmail.com');
INSERT INTO EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME,TITLE,REPORTSTO,BIRTHDATE,HIREDATE,
        ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,FAX,EMAIL) 
    VALUES (10,'Martinez','Chris','Associate',1,'06-JAN-87','30-APR-18','1421 Castlebrook Way',
        'Marietta','GA','USA','30066','+1 (678) 315-0629','+1 (678) 315-0629','cdm350@gmail.com');    
--Insert two new records into Customer table
INSERT INTO CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,COMPANY,ADDRESS,CITY,STATE,
        COUNTRY,POSTALCODE,PHONE,FAX,EMAIL,SUPPORTREPID) 
    VALUES (60,'Rodrigo','Blankenship','Revature','1600 Pennsylvania Ave','Hershey','PA',
        'USA','30066','+1 (678) 315-0629','+1 (678) 315-0629','cdm350@gmail.com',10);
INSERT INTO CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,COMPANY,ADDRESS,CITY,STATE,
        COUNTRY,POSTALCODE,PHONE,FAX,EMAIL,SUPPORTREPID) 
    VALUES (61,'Jake','Fromm','Revature','1604 Pennsylvania Ave','Hershey','PA',
        'USA','30066','+1 (678) 315-0635','+1 (678) 315-0635','jakeF@gmail.com',10);

---2.4 UPDATE
UPDATE CUSTOMER
SET FIRSTNAME = 'Robert', LASTNAME='Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME='Mitchell';
UPDATE ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

---2.5 LIKE
SELECT * 
FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';

---2.6 BETWEEN
SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 50;
SELECT * FROM EMPLOYEE 
    WHERE HIREDATE BETWEEN '01-JUN-03' AND '01-MAR-04';
    
---2.7 DELETE
DELETE FROM INVOICELINE WHERE INVOICEID IN 
    (SELECT INVOICEID FROM INVOICE WHERE CUSTOMERID IN 
        (SELECT CUSTOMERID FROM CUSTOMER WHERE FIRSTNAME ='Robert' AND LASTNAME = 'Walter')
    );
DELETE FROM INVOICE WHERE CUSTOMERID IN 
    (SELECT CUSTOMERID FROM CUSTOMER WHERE FIRSTNAME ='Robert' AND LASTNAME = 'Walter');
DELETE FROM CUSTOMER
    WHERE FIRSTNAME='Robert' AND LASTNAME='Walter';
    
---7.1 INNERJOIN
--Create an inner join that joins customers and orders and specifies the name of the customer and the invoiceId
SELECT CUSTOMER.FIRSTNAME, CUSTOMER.LASTNAME, INVOICE.INVOICEID
FROM CUSTOMER
INNER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

---7.2 OUTERJOIN
--Create an outer join that joins the customer and invoice table, specifying 
--the CustomerId, firstname, lastname, invoiceId, and total
SELECT CUSTOMER.CUSTOMERID, CUSTOMER.FIRSTNAME, CUSTOMER.LASTNAME, INVOICE.INVOICEID, INVOICE.TOTAL
FROM CUSTOMER
FULL OUTER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

---RIGHTJOIN
--Create a right join that joins album and artist specifying artist name and title
SELECT ALBUM.TITLE, ARTIST.NAME
FROM ALBUM
RIGHT JOIN ARTIST ON ALBUM.ARTISTID = ARTIST.ARTISTID;

---CROSSJOIN
--Create a cross join that joins album and artist and sorts by artist name in ascending order
SELECT * 
FROM ALBUM 
CROSS JOIN ARTIST ORDER BY ARTIST.NAME ASC;

---SELFJOIN
--Perform a self-join on the employee table, joining on the reportsto column
SELECT *
FROM EMPLOYEE A, EMPLOYEE B
WHERE A.REPORTSTO = B.REPORTSTO;




