--selecting all to see what data is already there
--2.1 Select
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

--2.2 Order by
SELECT * FROM ALBUM ORDER BY TITLE DESC;

SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

--selecting all to see what data is already there
--2.3 Insert into
SELECT * FROM GENRE;

INSERT INTO GENRE VALUES (26, 'Ska');
INSERT INTO GENRE VALUES (27, 'EDM');

INSERT INTO EMPLOYEE VALUES (9, 'Edwards', 'Jeremy', 'IT Staff', 6, TO_DATE('1993-06-03', 'yyyy-mm-dd'), TO_DATE('2015-05-23', 'yyyy-mm-dd'), '123 Sycamore NW', 'Washington', 'DC', 'USA', '20170', '+1 504-284-8616', '+1 504-284-8616', 'ebj@gmail.com');
INSERT INTO EMPLOYEE VALUES (10, 'Edwards', 'JDogg', 'IT Staff', 6, TO_DATE('1993-07-03', 'yyyy-mm-dd'), TO_DATE('2015-06-23', 'yyyy-mm-dd'), '1234 Sycamore NW', 'Washington', 'DC', 'USA', '20170', '+1 504-284-8616', '+1 504-284-8616', 'ebj2@gmail.com');

--selecting all to see what data is already there
SELECT * FROM CUSTOMER;

INSERT INTO customer VALUES (60, 'Jeremy', 'Edwards', 'Apple Inc.', '22 Dead End Ln', 'Portland', 'Oregon', 'USA', '50293', '504-284-8616', '504-284-8616', 'ebj@gmail.com', 3);
INSERT INTO customer VALUES (61, 'Jdogg', 'Edwards', 'Apple Inc.', 'Portland', '23 Dead End Ln', 'Oregon', 'USA', '50293', '504-284-8616', '504-284-8616', 'ebj2@gmail.com', 3);

--2.4 Update
UPDATE CUSTOMER SET FIRSTNAME = 'Robert', LASTNAME = 'Walter' WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';

SELECT * FROM ARTIST;

UPDATE ARTIST SET NAME = 'CCR' WHERE NAME = 'Creedence Clearwater Revival';

--2.5 Like
SELECT * FROM INVOICE;

SELECT BILLINGADDRESS FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';

--2.6 Between
SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 50;
SELECT * FROM EMPLOYEE WHERE HIREDATE BETWEEN TO_DATE('2003-06-01', 'YYYY-MM-DD') AND TO_DATE('2004-03-01', 'YYYY-MM-DD');

--2.7 Delete
SELECT * FROM INVOICELINE;
DELETE FROM INVOICELINE WHERE INVOICEID = 50;
DELETE FROM INVOICELINE WHERE INVOICEID = 61;
DELETE FROM INVOICELINE WHERE INVOICEID = 116;
DELETE FROM INVOICELINE WHERE INVOICEID = 245;
DELETE FROM INVOICELINE WHERE INVOICEID = 268;
DELETE FROM INVOICELINE WHERE INVOICEID = 290;
DELETE FROM INVOICELINE WHERE INVOICEID = 342;
DELETE FROM INVOICE WHERE CUSTOMERID = 32;
DELETE FROM CUSTOMER WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter';

--7.1 Inner
SELECT * FROM ORDER;
SELECT FIRSTNAME, LASTNAME, INVOICEID FROM CUSTOMER INNER JOIN INVOICE ON INVOICE.INVOICEID = CUSTOMER.CUSTOMERID;

--7.2 Outer
SELECT CUSTOMER.CUSTOMERID, FIRSTNAME, LASTNAME, INVOICEID, TOTAL FROM INVOICE OUTER JOIN CUSTOMER ON CUSTOMER.CUSTOMERID = INVOICEID;

--7.3 Right
SELECT ALBUM.TITLE, ARTIST.NAME FROM ALBUM RIGHT OUTER JOIN ARTIST ON ALBUM.ARTISTID = ARTIST.ARTISTID;

--7.4 Cross
SELECT * FROM ARTIST CROSS JOIN ALBUM ORDER BY ARTIST.NAME;

--7.5 Self
SELECT * FROM EMPLOYEE e1, EMPLOYEE e2 WHERE  e1.REPORTSTO = e2.REPORTSTO;